### ISSUE TITLE
activate CI target to apply the chart

### ISSUE THREAD

**Issue by danduk82** [camptocamp/helm-qwc-services#1]
I had to remove 
```yaml
       - name: Setup k3s/k3d
         run: c2cciutils-k8s-install

       - name: Apply
         run: kubectl apply -f tests/expected.yaml
```
from the main ci run, because of the v-qwc-data shenanigans, we should find a clean way to re-activate it.
